### ISSUE TITLE
ValidationException error - missing 'license_title'

### ISSUE THREAD

**Issue by jdarnold** [simon-weber/Unofficial-Google-Music-API#304]
Just writing a simple playlist program and I'm getting the following error when using `search_all_access` :

```python
{'url': 'https://mclients.googleapis.com/sj/v1.10/query', 'headers': {'Authorization': '<omitted>'}, 'params': {'q': u'Lucinda Williams', 'max-results': 100}, 'method': 'GET'}

'{\n "kind": "sj#searchresponse",\n "entries": [\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n    "name": "Lucinda Williams",\n    "artistArtRef": "http://lh4.ggpht.com/l2uOvpAZtvMxmzlzQWH0YdO1ylFIdauPiUCCwBxQcEhHRDX4PRjA5PuVewKUYG04U2mAVvm9XQ",\n    "artistId": "Ag2pszhksprucai7s5rw5fm32jm",\n    "artist_bio_attribution": {\n     "kind": "sj#attribution",\n     "source_title": "Provided by artist representative"\n    }\n   },\n   "score": 717.6569213867188,\n   "best_result": true,\n   "navigational_result": true,\n   "navigational_confidence": 10.0\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Down Where the Spirit Meets the Bone",\n    "albumArtist": "Lucinda Williams",\n    "albumArtRef": "http://lh5.ggpht.com/MVRx0zZ-OuWf-z70BsHGmRFeLTjnSOgR1zRY85JsEDg3q5kS0M0-lyqUCt4mq6IGnf5HkuYy0_s",\n    "albumId": "Btpb2jrnrjcvi32ihpkoihu2m3i",\n    "artist": "Lucinda Williams",\n    "artistId": [\n     "Ag2pszhksprucai7s5rw5fm32jm"\n    ],\n    "year": 2014\n   },\n   "sc...'

A traceback follows:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 249, in perform
    cls.validate(response, parsed_response)
  File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/mobileclient.py", line 258, in validate
    return validictory.validate(msg, cls._res_schema)
  File "/usr/lib/python2.7/site-packages/validictory/__init__.py", line 33, in validate
    return v.validate(data, schema)
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 569, in validate
    self._validate(data, schema)
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 572, in _validate
    self.__validate("_data", {"_data": data}, schema)
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 603, in __validate
    newschema.get(schemaprop))
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 230, in validate_properties
    properties.get(eachProp))
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 603, in __validate
    newschema.get(schemaprop))
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 276, in validate_items
    e.value)
ValidationException: Failed to validate field 'entries' list schema: Required field 'license_title' is missing
```

**Comment by simon-weber** [comment]
Thanks for reporting this! I'll fix it soon.

**Comment by jdarnold** [comment]
Also getting it for source_url:

```python
Failed to validate field 'entries' list schema: Value u'' for field 'source_url' cannot be blank'

First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](http://goo.gl/qbAW8) that includes the above ValidationException and the following request/response:
{'url': 'https://mclients.googleapis.com/sj/v1.10/query', 'headers': {'Authorization': '<omitted>'}, 'params': {'q': u'Vanishing Point', 'max-results': 100}, 'method': 'GET'}

'{\n "kind": "sj#searchresponse",\n "entries": [\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n    "name": "Vanishing Point",\n    "artistArtRef": "http://lh4.ggpht.com/bcinklRUrdeSp-a5ZKeiO7oYlqR_jc0ZsqLih26Dos4A2tfYwTItNmZOoAEuT0KnCTJYSApWYw",\n    "artistId": "A56qdnsx7m4suaowxbimbuahfhq",\n    "artist_bio_attribution": {\n     "kind": "sj#attribution",\n     "source_title": "Wikipedia",\n     "source_url": "http://en.wikipedia.org/wiki/Vanishing_Point_(band)",\n     "license_title": "Creative Commons Attribution CC-BY-SA 4.0",\n     "license_url": "http://creativecommons.org/licenses/by-sa/4.0/legalcode"\n    }\n   },\n   "score": 322.3014221191406,\n   "navigational_result": true,\n   "navigational_confidence": 5.411051344392521\n  },\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n    "name": "New Order",\n    "artistArtRef": "http://lh5.ggpht.com/0eF54zbh8YU22pkBZ_N2WgYXgo7ZQGvehqmsgAtLK118chs6jeTYsUaUwqPnr6dFbK_OvI8mrbU",\n    "artistId": "Abaq3zyhvrmpvs62htmzlv6bdna",\n ...'

A traceback follows:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 249, in perform
    cls.validate(response, parsed_response)
  File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/mobileclient.py", line 258, in validate
    return validictory.validate(msg, cls._res_schema)
  File "/usr/lib/python2.7/site-packages/validictory/__init__.py", line 33, in validate
    return v.validate(data, schema)
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 569, in validate
    self._validate(data, schema)
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 572, in _validate
    self.__validate("_data", {"_data": data}, schema)
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 603, in __validate
    newschema.get(schemaprop))
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 230, in validate_properties
    properties.get(eachProp))
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 603, in __validate
    newschema.get(schemaprop))
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 276, in validate_items
    e.value)
ValidationException: Failed to validate field 'entries' list schema: Value u'' for field 'source_url' cannot be blank'
```

**Comment by simon-weber** [comment]
Thanks again for reporting this! The All Access schemas are toughest to pin down.

**Comment by jdarnold** [comment]
I had to add the 'required': False to license_url and source_url fields as well. Sorry for not noticing those.

**Comment by jdarnold** [comment]
And a 'blank':True to the source_title

**Comment by simon-weber** [comment]
Great; thanks.
