### ISSUE TITLE
Authentication (future) issues

### ISSUE THREAD

**Issue by rollet** [simon-weber/Unofficial-Google-Music-API#323]
Hi,
ClientLogin is deprecated from  April 20, 2012 and will be shutdown on April, 20, 2015 according to Google [https://developers.google.com/accounts/docs/AuthForInstalledApps]. MobileClient and WebClient interfaces seem to be based on that authentication scheme, so is there any plan to move to oauth2.0 ? 
Thanks and regards,
Romain

**Comment by thebigmunch** [comment]
There are already multiple issues regarding this. An issue search for ``ClientLogin`` will direct you to them. They have all the information you're looking for.

**Comment by simon-weber** [comment]
The mobileclient issue is https://github.com/simon-weber/Unofficial-Google-Music-API/issues/168, and the webclient issue is https://github.com/simon-weber/Unofficial-Google-Music-API/issues/318.

**Comment by sciencepro** [comment]
For what it's worth, login continues to work today.  Either it hasn't been disabled yet or some weird loophole is present.

**Comment by simon-weber** [comment]
Thanks for checking :+1:

**Comment by timtebeek** [comment]
Seems broken now.. Testing with a new application password:
```python
    # Connect to Google music
    client = Mobileclient()
    logging.info('Logging in \'%s\'to Google Music', google_user_id)
    assert client.login(google_user_id, google_app_password)
```
results in:
```
Traceback (most recent call last):
  File "src/test/playlist_test.py", line 13, in test
    spotify2gmusic.main()
  File "src/spotify2gmusic.py", line 18, in main
    gmusic(name, tracks)
  File "src/spotify2gmusic.py", line 53, in gmusic
    assert client.login(google_user_id, google_app_password)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 39, in login
    if not self.session.login(email, password):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 147, in login
    success = super(Mobileclient, self).login(email, password, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 122, in login
    webclient.Init.perform(self, True)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 208, in perform
    response = session.send(req_kwargs, cls.required_auth)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 86, in send
    res = self._send_with_auth(req_kwargs, desired_auth, rsession)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 142, in _send_with_auth
    return rsession.request(**req_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 605, in send
    r.content
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 750, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 673, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 304, in stream
    for line in self.read_chunked(amt):
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 411, in read_chunked
    raise httplib.IncompleteRead(''.join(line))
IncompleteRead: IncompleteRead(0 bytes read)
```

**Comment by thebigmunch** [comment]
Login still works fine for me with both Webclient and Mobileclient.

**Comment by bobby-lindsey** [comment]
I'm having the same issue as timtebeek. I believe Google deprecated a lot of their APIs on the 04/20/15 forcing new APIs to use OAuth 2.0. Not sure if this affects the way the API authenticates.

**Comment by timtebeek** [comment]
@bobby-lindsey Turns out one can just catch the `IncomleteRead`, which times out after five minutes, and continue after.. Kinda annoying, but it might get you going:
```python
     # Connect to Google music
     client = Mobileclient()
     try:
         assert client.login(google_user_id, google_app_password)
     except httplib.IncompleteRead as err:
         logging.info(err)
```

**Comment by bobby-lindsey** [comment]
@timtebeek Thanks for the suggestion, I think that should work for now.

**Comment by simon-weber** [comment]
The mobileclient has been moved to oauth.

I can still log in fine with the webclient, though I'm planning to switch it away from clientlogin once I have a chance. Watch https://github.com/simon-weber/Unofficial-Google-Music-API/issues/318 for updates on that front.
