### ISSUE TITLE
Issues with get_album_info()

### ISSUE THREAD

**Issue by prophaner** [simon-weber/Unofficial-Google-Music-API#332]
I tried with several names, same error:

In[11]: api.get_album_info('Countdown To Extinction')
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-5ebcdcab93c1>", line 1, in <module>
    api.get_album_info('Countdown To Extinction')
  File "<string>", line 2, in get_album_info
  File "C:\Python27\lib\site-packages\gmusicapi\utils\utils.py", line 288, in wrapper
    return function(*args, **kw)
  File "C:\Python27\lib\site-packages\gmusicapi\clients\mobileclient.py", line 972, in get_album_info
    return self._make_call(mobileclient.GetAlbum, album_id, include_tracks)
  File "C:\Python27\lib\site-packages\gmusicapi\clients\shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "C:\Python27\lib\site-packages\gmusicapi\protocol\shared.py", line 225, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: GetAlbum: 400 Client Error: Bad Request
(requests kwargs: {'url': 'https://www.googleapis.com/sj/v1.5/fetchalbum', 'headers': {'Authorization': '<omitted>'}, 'params': {'alt': 'json', 'nid': 'Countdown To Extinction', 'include-tracks': True}, 'method': 'GET'})
(response was: '{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "badRequest",\n    "message": "Bad Request"\n   }\n  ],\n  "code": 400,\n  "message": "Bad Request"\n }\n}\n')

**Comment by simon-weber** [comment]
Can you try this again with the code from the develop branch? It's a bit more up to date, so this might already be fixed.

**Comment by simon-weber** [comment]
Feel free to reopen if this is still a problem!
