### ISSUE TITLE
Validation Exception

### ISSUE THREAD

**Issue by chrisnorman7** [simon-weber/Unofficial-Google-Music-API#333]
Not sure what this means, but the warning said to report, so here goes:

2015-05-16 10:36:29,872 - gmusicapi.Mobileclient1 (shared:282) [ERROR]: the response format for GetArtist was not recognized.

Required field 'source_title' is missing

First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](http://goo.gl/qbAW8) that includes the above ValidationException and the following request/response:
{'url': 'https://mclients.googleapis.com/sj/v1.11/fetchartist', 'headers': {'Authorization': '<omitted>'}, 'params': {'nid': u'Adg34pnrw4k65yuyr7enp5xvbuy', 'num-top-tracks': 5, 'num-related-artists': 5, 'alt': 'json', 'include-albums': True}, 'method': 'GET'}

'{\n "kind": "sj#artist",\n "name": "Crossfire",\n "artistArtRef": "http://lh3.googleusercontent.com/uHZTLSWixDOpoyoTxZujz7PLKUH6wWWIAMmwEG5IP24bm9QcB1f18e1WIuktOCmLtkQ5t-Bwvg",\n "artistId": "Adg34pnrw4k65yuyr7enp5xvbuy",\n "artistBio": "Crossfire is a musical group.",\n "artist_bio_attribution": {\n  "kind": "sj#attribution"\n },\n "albums": [\n  {\n   "kind": "sj#album",\n   "name": "See You in Hell",\n   "albumArtist": "Crossfire",\n   "albumArtRef": "http://lh3.ggpht.com/ISpGo9mbr5uu56HK3mdlMpQpQ6dkI7mAgz_KcM6eX2CPrBg84PaBnW39Z8QM1eK_2XTG7KjpLg",\n   "albumId": "Bcvkr5yo2dyes4hldzoqo7uizje",\n   "artist": "Crossfire",\n   "artistId": [\n    "Adg34pnrw4k65yuyr7enp5xvbuy"\n   ],\n   "year": 2014\n  },\n  {\n   "kind": "sj#album",\n   "name": "Alive and Well",\n   "albumArtist": "Crossfire",\n   "albumArtRef": "http://lh5.ggpht.com/ACHAM1s6E6uC-6HfwQbQlvtrQwuIHDi2Lf7K6Q2RcjIyB9zoNcVZL0mCETOEZmT9MGJXJFoXLA",\n   "albumId": "Bvfhl47rorthm4tz44sn7vhefea",\n   "artist": "Crossfire",\n   "artistId": [\n    "Adg34pnrw4k...'

A traceback follows:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gmusicapi-5.0.0.dev0-py2.7.egg/gmusicapi/protocol/shared.py", line 249, in perform
    cls.validate(response, parsed_response)
  File "/usr/local/lib/python2.7/site-packages/gmusicapi-5.0.0.dev0-py2.7.egg/gmusicapi/protocol/mobileclient.py", line 262, in validate
    return validictory.validate(msg, cls._res_schema)
  File "/usr/local/lib/python2.7/site-packages/validictory/__init__.py", line 36, in validate
    return v.validate(data, schema)
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 543, in validate
    self.__validate("data", {"data": data}, schema, '<obj>')
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 244, in validate_properties
    path + '.' + eachProp)
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 244, in validate_properties
    path + '.' + eachProp)
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 285, in validate_required
    exctype=RequiredFieldValidationError)
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 176, in _error
    raise err
ValidationException: Required field 'source_title' is missing

**Comment by simon-weber** [comment]
Great, thanks. Looks like an easy change.

**Comment by chrisnorman7** [comment]
Glad it made sense to you! :-)

Cheers,

Take care,
Chris Norman
chris.norman2@googlemail.com
