### ISSUE TITLE
Webclient.login hangs on Windows

### ISSUE THREAD

**Issue by chrisnorman7** [simon-weber/Unofficial-Google-Music-API#336]
When calling Webclient.login() on windows, it just hangs for a very long time... I'm not sure about indefinitely, but it's been sat here for about 4 minutes so far, no timeout or anything.

Cheers.

**Comment by simon-weber** [comment]
That's odd. Webclient login is likely to change significantly in the future (https://github.com/simon-weber/Unofficial-Google-Music-API/issues/318), so hopefully this gets fixed along with it.

**Comment by chrisnorman7** [comment]
OK, so I just ran my app on a PC running Windows 7 (rather than 8 at home), and it worked perfectly... I'm going to try and find some other people with windows 8 / 8.1 to test, unless you know it already works on those platforms.

Hope this isn't just a one-off with my machine, that would be pretty irritating.

**Comment by chrisnorman7** [comment]
OK, I'm running Windows 8 (64 BIT).

Here's the traceback I get:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\gmusicapi-5.0.0.dev0-py2.7.egg\gmusicapi\clients\webclient.py", line 60, in login
    if not self.session.login(email, password):
  File "C:\Python27\lib\site-packages\gmusicapi-5.0.0.dev0-py2.7.egg\gmusicapi\session.py", line 123, in login
    webclient.Init.perform(self, True)
  File "C:\Python27\lib\site-packages\gmusicapi-5.0.0.dev0-py2.7.egg\gmusicapi\protocol\shared.py", line 209, in perform
    response = session.send(req_kwargs, cls.required_auth)
  File "C:\Python27\lib\site-packages\gmusicapi-5.0.0.dev0-py2.7.egg\gmusicapi\session.py", line 87, in send
    res = self._send_with_auth(req_kwargs, desired_auth, rsession)
  File "C:\Python27\lib\site-packages\gmusicapi-5.0.0.dev0-py2.7.egg\gmusicapi\session.py", line 143, in _send_with_auth
    return rsession.request(**req_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 605, in send
    r.content
  File "C:\Python27\lib\site-packages\requests\models.py", line 750, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\Python27\lib\site-packages\requests\models.py", line 673, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\response.py", line 304, in stream
    for line in self.read_chunked(amt):
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\response.py", line 411, in read_chunked
    raise httplib.IncompleteRead(''.join(line))
httplib.IncompleteRead: IncompleteRead(0 bytes read)

That was from:
from gmusicapi import Webclient
w = Webclient()
w.login('username', 'password')

HTH.

**Comment by chrisnorman7** [comment]
OK, pip uninstall and re-install requests fixes it.

**Comment by chrisnorman7** [comment]
It's fixed, apparently it was a problem with requests on my machine.
