### ISSUE TITLE
Mobileclient.get_promoted_songs causes a traceback

### ISSUE THREAD

**Issue by chrisnorman7** [simon-weber/Unofficial-Google-Music-API#337]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/gmusicapi-5.0.0.dev0-py2.7.egg/gmusicapi/clients/mobileclient.py", line 644, in get_promoted_songs
    updated_after=None)
  File "/usr/local/lib/python2.7/site-packages/gmusicapi-5.0.0.dev0-py2.7.egg/gmusicapi/clients/mobileclient.py", line 1020, in _get_all_items
    return [s for chunk in generator for s in chunk]
  File "/usr/local/lib/python2.7/site-packages/gmusicapi-5.0.0.dev0-py2.7.egg/gmusicapi/clients/mobileclient.py", line 1038, in _get_all_items_incremental
    items = [item for item in items if not item['deleted']]
KeyError: 'deleted'

Does this replace Mobileclient.get_thumbs_up_songs?

Cheers.

**Comment by riggs-** [comment]
get_promoted_songs() used to work fine until 4-5 days ago. Since then the KeyError exception you mentioned gets thrown.

The function did never return the full list of "thumbs up songs". In my observations it returns a list of songs that you rated (usually by a "thumbs up"-click) but are NOT part of "My Library".

You could generate the list of "thumbs up songs" by doing something like:
```python
thumbs_up = [i for i in get_all_songs()+get_promoted_songs() if 'rating' in i.keys() and int(i['rating']) == 5]
```

Hope this helps as soon as get_thumbs_up_songs() works again :-)

**Comment by chrisnorman7** [comment]
Great stuff, thanks for the heads up.

Cheers,
