### ISSUE TITLE
the response format for Search was not recognized.

### ISSUE THREAD

**Issue by JVMed** [simon-weber/Unofficial-Google-Music-API#341]
I think this is an unreported issue.

Below is one instance of the error occurring on Windows 8.1:

```python
gmusicapi.Mobileclient1 (shared:282) [ERROR]: the response format for Search was not recognized.

Value {u'kind': u'sj#searchresponse', u'clusterOrder': [u'5', u'2', u'3', u'1', u'7', u'6', u'4', u'8'], u'entries
': [{u'navigational_result': True, u'navigational_confidence': 10.0, u'score': 370.8509216308594, u'type': u'2', u
'artist': {u'kind': u'sj#artist', u'artistArtRef': u'http://lh3.googleusercontent.com/gzZC6tzfMCoOdhSi_Q5rAXcUrTfZ
IQVpT_vdTJH-zhecffCY32l0IaT6OqJRwZj3AVPst9h4wQw', u'name': u'Muse', u'artistId': u'A2yuzeawfml3ribpb7n3gq5nb4y', u
'artist_bio_attribution': {u'license_url': u'http://creativecommons.org/licenses/by-sa/4.0/legalcode', u'kind': u'
sj#attribution', u'license_title': u'Creative Commons Attribution CC-BY-SA 4.0', u'source_title': u'Wikipedia', u'
source_url': u'http://en.wikipedia.org/wiki/Muse_(band)'}}}, {u'album': {u'kind': u'sj#album', u'name': u'Psycho',
 u'artist': u'Muse', u'albumArtRef': u'http://lh3.googleusercontent.com/xkX5srHGYEZ3FGxfdKcga0S_Zahin8mslr35Bgrs3U
747vgx7IUo1ESK4pDtPQy2SjVBMHJT_A', u'albumId': u'Bwzuvqeszzwian67456yx4ciake', u'artistId': [u'A2yuzeawfml3ribpb7n
3gq5nb4y'], u'albumArtist': u'Muse', u'year': 2015}, u'navigational_result': True, u'score': 576.7113037109375, u'
type': u'3', u'navigational_confidence': 10.0}, {u'track': {u'rating': u'4', u'albumArtRef': [{u'url': u'http://lh
3.googleusercontent.com/xkX5srHGYEZ3FGxfdKcga0S_Zahin8mslr35Bgrs3U747vgx7IUo1ESK4pDtPQy2SjVBMHJT_A'}], u'lastRatin
gChangeTimestamp': u'1427154552136000', u'artistId': [u'A2yuzeawfml3ribpb7n3gq5nb4y'], u'composer': u'', u'year':
2015, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Psycho', u'title': u'Psycho', u'albu
mArtist': u'Muse', u'trackNumber': 1, u'discNumber': 1, u'albumAvailableForPurchase': True, u'contentType': u'1',
u'trackAvailableForPurchase': True, u'storeId': u'Tzenzxydbbn4yijzzy6kk4kmrqy', u'nid': u'Tzenzxydbbn4yijzzy6kk4km
rqy', u'estimatedSize': u'12671504', u'albumId': u'Bwzuvqeszzwian67456yx4ciake', u'genre': u"'10s Alternative", u'
playCount': 6, u'kind': u'sj#track', u'artist': u'Muse', u'durationMillis': u'316000'}, u'navigational_confidence'
: 77.81393741908815, u'navigational_result': True, u'score': 688.8449096679688, u'best_result': True, u'type': u'1
'}, {u'track': {u'album': u'Nonolimite & Les Psycho Potes', u'kind': u'sj#track', u'storeId': u'Tky6lfnmujpivohkvk
pfsdqt7si', u'contentType': u'2', u'artist': u'Nonolimite & Les Psycho Potes', u'albumArtRef': [{u'url': u'http://
lh5.ggpht.com/Y05KHAMz8_gK7YIZTtdqbSyuSWnAr-4br3R527YTWoCh0bC5I9xF280pv8mh5jXFYAbPTkkI'}], u'title': u'Ma zic! Ma
muse!', u'nid': u'Tky6lfnmujpivohkvkpfsdqt7si', u'estimatedSize': u'6993529', u'albumId': u'Bpk2sfy5n6rfsl6fkefw7l
bobum', u'artistId': [u'Avdw44dijdntokdsqdugyyx3spe'], u'albumArtist': u'Nonolimite & Les Psycho Potes', u'duratio
nMillis': u'174000', u'composer': u'', u'trackAvailableForSubscription': True, u'genre': u'Rock', u'trackNumber':
1, u'discNumber': 2, u'trackAvailableForPurchase': True, u'trackType': u'7', u'albumAvailableForPurchase': True},
u'score': 17.70492172241211, u'type': u'1'}, {u'track': {u'albumArtRef': [{u'url': u'http://lh3.googleusercontent.
com/t7FBqJ40poXBre1Oh45IRlw2ld2d39zpIh8zFArYqj6LIyzLhUCQJQCwijF1hrYi7D7DprZCwA'}], u'artistId': [u'Aqjvcov7pnfrguz
vgq6pmblyv3i'], u'composer': u'New Tribute Kings', u'year': 2015, u'trackAvailableForSubscription': True, u'trackT
ype': u'7', u'album': u"It's the Hits! 2015, Vol.8", u'title': u'Psycho Originally Performed By Muse (Tribute Vers
ion)', u'albumArtist': u'New Tribute Kings', u'trackNumber': 17, u'discNumber': 1, u'albumAvailableForPurchase': T
rue, u'contentType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'Twpbruo5pfmsiu4xuohqgnrwu5i', u'nid':
 u'Twpbruo5pfmsiu4xuohqgnrwu5i', u'estimatedSize': u'12802116', u'albumId': u'Blubabj5cs74pl6swdq5lvpwaki', u'genr
e': u'Pop', u'kind': u'sj#track', u'artist': u'New Tribute Kings', u'durationMillis': u'319000'}, u'score': 6.9122
52426147461, u'type': u'1'}, {u'track': {u'albumArtRef': [{u'url': u'http://lh3.googleusercontent.com/qB2I_yI6YjNn
yIapU4ONITtycM-vHkLXVUoD4QObKbAJygvx5vqf6UNUrTyfQSP89Bv-W6emsQ'}], u'artistId': [u'Ab273mwgwgwsqwwegimadwa735e'],
u'composer': u'Sunfly Karaoke', u'year': 2015, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album
': u'Sunfly Hits - April 2015', u'title': u'Psycho Originally Performed By Muse (Karaoke Version)', u'albumArtist'
: u'Sunfly Karaoke', u'trackNumber': 3, u'discNumber': 1, u'albumAvailableForPurchase': True, u'contentType': u'2'
, u'trackAvailableForPurchase': True, u'storeId': u'Ti3wqr27hblnxfb7ouz5b6jeyvi', u'nid': u'Ti3wqr27hblnxfb7ouz5b6
jeyvi', u'estimatedSize': u'12802116', u'albumId': u'Bpyxmees4iiwzxattlk3drx62tq', u'genre': u'Pop', u'kind': u'sj
#track', u'artist': u'Sunfly Karaoke', u'durationMillis': u'319000'}, u'score': 4.106845855712891, u'type': u'1'},
 {u'track': {u'albumArtRef': [{u'url': u'http://lh3.googleusercontent.com/LeZB8QKPz6uu4shznaj4RzSh9tR1vTJPdAOGwzWB
9Dy8SJ0bBLkczk6rSy4tP7R6W90qg9zns-U'}], u'artistId': [u'Aa757ym33iijs7o3lbgjsje45fa'], u'composer': u'DJ MixMaster
s', u'year': 2015, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Chart Ringtones #42', u
'title': u'Psycho Originally Performed By Muse (Tribute Version)', u'albumArtist': u'DJ MixMasters', u'trackNumber
': 17, u'discNumber': 1, u'albumAvailableForPurchase': True, u'contentType': u'2', u'trackAvailableForPurchase': T
rue, u'storeId': u'Ticglcnc4d6rhupzpmqrinsgzde', u'nid': u'Ticglcnc4d6rhupzpmqrinsgzde', u'estimatedSize': u'11222
47', u'albumId': u'Bgk7gmjxljdwxsmncsbcno7xxia', u'genre': u'Pop', u'kind': u'sj#track', u'artist': u'DJ MixMaster
s', u'durationMillis': u'28000'}, u'score': 2.762075662612915, u'type': u'1'}]} for field '<obj>' contains additio
nal property 'clusterOrder' not defined by 'properties' or 'patternProperties' and additionalProperties  is False

First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](h
ttp://goo.gl/qbAW8) that includes the above ValidationException and the following request/response:
{'url': 'https://mclients.googleapis.com/sj/v1.11/query', 'headers': {'Authorization': '<omitted>'}, 'params': {'q
': 'Psycho Muse', 'max-results': 10}, 'method': 'GET'}

'{\n "kind": "sj#searchresponse",\n "entries": [\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n
    "name": "Muse",\n    "artistArtRef": "http://lh3.googleusercontent.com/gzZC6tzfMCoOdhSi_Q5rAXcUrTfZIQVpT_vdTJH
-zhecffCY32l0IaT6OqJRwZj3AVPst9h4wQw",\n    "artistId": "A2yuzeawfml3ribpb7n3gq5nb4y",\n    "artist_bio_attributio
n": {\n     "kind": "sj#attribution",\n     "source_title": "Wikipedia",\n     "source_url": "http://en.wikipedia.
org/wiki/Muse_(band)",\n     "license_title": "Creative Commons Attribution CC-BY-SA 4.0",\n     "license_url": "h
ttp://creativecommons.org/licenses/by-sa/4.0/legalcode"\n    }\n   },\n   "score": 370.8509216308594,\n   "navigat
ional_result": true,\n   "navigational_confidence": 10.0\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "
sj#album",\n    "name": "Psycho",\n    "albumArtist": "Muse",\n    "albumArtRef": "http://lh3.googleusercontent.co
m/xkX5srHGYEZ3FGxfdKcga0S_Zahin8mslr35Bgrs3U747vgx7IUo1ESK4pDtPQy2SjVBMHJT_A",\n    "albumId": "Bwzuvqeszzwian6745
6yx4...'

A traceback follows:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gmusicapi-5.0.0_dev-py2.7.egg\gmusicapi\protocol\shared.py", line 249, in pe
rform
    cls.validate(response, parsed_response)
  File "C:\Python27\lib\site-packages\gmusicapi-5.0.0_dev-py2.7.egg\gmusicapi\protocol\mobileclient.py", line 262,
 in validate
    return validictory.validate(msg, cls._res_schema)
  File "C:\Python27\lib\site-packages\validictory\__init__.py", line 36, in validate
    return v.validate(data, schema)
  File "C:\Python27\lib\site-packages\validictory\validator.py", line 543, in validate
    self.__validate("data", {"data": data}, schema, '<obj>')
  File "C:\Python27\lib\site-packages\validictory\validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "C:\Python27\lib\site-packages\validictory\validator.py", line 353, in validate_additionalProperties
    " is False", value, fieldname, prop=eachProperty, path=path)
  File "C:\Python27\lib\site-packages\validictory\validator.py", line 176, in _error
    raise err
ValidationException: Value {u'kind': u'sj#searchresponse', u'clusterOrder': [u'5', u'2', u'3', u'1', u'7', u'6', u
'4', u'8'], u'entries': [{u'navigational_result': True, u'navigational_confidence': 10.0, u'score': 370.8509216308
594, u'type': u'2', u'artist': {u'kind': u'sj#artist', u'artistArtRef': u'http://lh3.googleusercontent.com/gzZC6tz
fMCoOdhSi_Q5rAXcUrTfZIQVpT_vdTJH-zhecffCY32l0IaT6OqJRwZj3AVPst9h4wQw', u'name': u'Muse', u'artistId': u'A2yuzeawfm
l3ribpb7n3gq5nb4y', u'artist_bio_attribution': {u'license_url': u'http://creativecommons.org/licenses/by-sa/4.0/le
galcode', u'kind': u'sj#attribution', u'license_title': u'Creative Commons Attribution CC-BY-SA 4.0', u'source_tit
le': u'Wikipedia', u'source_url': u'http://en.wikipedia.org/wiki/Muse_(band)'}}}, {u'album': {u'kind': u'sj#album'
, u'name': u'Psycho', u'artist': u'Muse', u'albumArtRef': u'http://lh3.googleusercontent.com/xkX5srHGYEZ3FGxfdKcga
0S_Zahin8mslr35Bgrs3U747vgx7IUo1ESK4pDtPQy2SjVBMHJT_A', u'albumId': u'Bwzuvqeszzwian67456yx4ciake', u'artistId': [
u'A2yuzeawfml3ribpb7n3gq5nb4y'], u'albumArtist': u'Muse', u'year': 2015}, u'navigational_result': True, u'score':
576.7113037109375, u'type': u'3', u'navigational_confidence': 10.0}, {u'track': {u'rating': u'4', u'albumArtRef':
[{u'url': u'http://lh3.googleusercontent.com/xkX5srHGYEZ3FGxfdKcga0S_Zahin8mslr35Bgrs3U747vgx7IUo1ESK4pDtPQy2SjVBM
HJT_A'}], u'lastRatingChangeTimestamp': u'1427154552136000', u'artistId': [u'A2yuzeawfml3ribpb7n3gq5nb4y'], u'comp
oser': u'', u'year': 2015, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Psycho', u'titl
e': u'Psycho', u'albumArtist': u'Muse', u'trackNumber': 1, u'discNumber': 1, u'albumAvailableForPurchase': True, u
'contentType': u'1', u'trackAvailableForPurchase': True, u'storeId': u'Tzenzxydbbn4yijzzy6kk4kmrqy', u'nid': u'Tze
nzxydbbn4yijzzy6kk4kmrqy', u'estimatedSize': u'12671504', u'albumId': u'Bwzuvqeszzwian67456yx4ciake', u'genre': u"
'10s Alternative", u'playCount': 6, u'kind': u'sj#track', u'artist': u'Muse', u'durationMillis': u'316000'}, u'nav
igational_confidence': 77.81393741908815, u'navigational_result': True, u'score': 688.8449096679688, u'best_result
': True, u'type': u'1'}, {u'track': {u'album': u'Nonolimite & Les Psycho Potes', u'kind': u'sj#track', u'storeId':
 u'Tky6lfnmujpivohkvkpfsdqt7si', u'contentType': u'2', u'artist': u'Nonolimite & Les Psycho Potes', u'albumArtRef'
: [{u'url': u'http://lh5.ggpht.com/Y05KHAMz8_gK7YIZTtdqbSyuSWnAr-4br3R527YTWoCh0bC5I9xF280pv8mh5jXFYAbPTkkI'}], u'
title': u'Ma zic! Ma muse!', u'nid': u'Tky6lfnmujpivohkvkpfsdqt7si', u'estimatedSize': u'6993529', u'albumId': u'B
pk2sfy5n6rfsl6fkefw7lbobum', u'artistId': [u'Avdw44dijdntokdsqdugyyx3spe'], u'albumArtist': u'Nonolimite & Les Psy
cho Potes', u'durationMillis': u'174000', u'composer': u'', u'trackAvailableForSubscription': True, u'genre': u'Ro
ck', u'trackNumber': 1, u'discNumber': 2, u'trackAvailableForPurchase': True, u'trackType': u'7', u'albumAvailable
ForPurchase': True}, u'score': 17.70492172241211, u'type': u'1'}, {u'track': {u'albumArtRef': [{u'url': u'http://l
h3.googleusercontent.com/t7FBqJ40poXBre1Oh45IRlw2ld2d39zpIh8zFArYqj6LIyzLhUCQJQCwijF1hrYi7D7DprZCwA'}], u'artistId
': [u'Aqjvcov7pnfrguzvgq6pmblyv3i'], u'composer': u'New Tribute Kings', u'year': 2015, u'trackAvailableForSubscrip
tion': True, u'trackType': u'7', u'album': u"It's the Hits! 2015, Vol.8", u'title': u'Psycho Originally Performed
By Muse (Tribute Version)', u'albumArtist': u'New Tribute Kings', u'trackNumber': 17, u'discNumber': 1, u'albumAva
ilableForPurchase': True, u'contentType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'Twpbruo5pfmsiu4x
uohqgnrwu5i', u'nid': u'Twpbruo5pfmsiu4xuohqgnrwu5i', u'estimatedSize': u'12802116', u'albumId': u'Blubabj5cs74pl6
swdq5lvpwaki', u'genre': u'Pop', u'kind': u'sj#track', u'artist': u'New Tribute Kings', u'durationMillis': u'31900
0'}, u'score': 6.912252426147461, u'type': u'1'}, {u'track': {u'albumArtRef': [{u'url': u'http://lh3.googleusercon
tent.com/qB2I_yI6YjNnyIapU4ONITtycM-vHkLXVUoD4QObKbAJygvx5vqf6UNUrTyfQSP89Bv-W6emsQ'}], u'artistId': [u'Ab273mwgwg
wsqwwegimadwa735e'], u'composer': u'Sunfly Karaoke', u'year': 2015, u'trackAvailableForSubscription': True, u'trac
kType': u'7', u'album': u'Sunfly Hits - April 2015', u'title': u'Psycho Originally Performed By Muse (Karaoke Vers
ion)', u'albumArtist': u'Sunfly Karaoke', u'trackNumber': 3, u'discNumber': 1, u'albumAvailableForPurchase': True,
 u'contentType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'Ti3wqr27hblnxfb7ouz5b6jeyvi', u'nid': u'T
i3wqr27hblnxfb7ouz5b6jeyvi', u'estimatedSize': u'12802116', u'albumId': u'Bpyxmees4iiwzxattlk3drx62tq', u'genre':
u'Pop', u'kind': u'sj#track', u'artist': u'Sunfly Karaoke', u'durationMillis': u'319000'}, u'score': 4.10684585571
2891, u'type': u'1'}, {u'track': {u'albumArtRef': [{u'url': u'http://lh3.googleusercontent.com/LeZB8QKPz6uu4shznaj
4RzSh9tR1vTJPdAOGwzWB9Dy8SJ0bBLkczk6rSy4tP7R6W90qg9zns-U'}], u'artistId': [u'Aa757ym33iijs7o3lbgjsje45fa'], u'comp
oser': u'DJ MixMasters', u'year': 2015, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Ch
art Ringtones #42', u'title': u'Psycho Originally Performed By Muse (Tribute Version)', u'albumArtist': u'DJ MixMa
sters', u'trackNumber': 17, u'discNumber': 1, u'albumAvailableForPurchase': True, u'contentType': u'2', u'trackAva
ilableForPurchase': True, u'storeId': u'Ticglcnc4d6rhupzpmqrinsgzde', u'nid': u'Ticglcnc4d6rhupzpmqrinsgzde', u'es
timatedSize': u'1122247', u'albumId': u'Bgk7gmjxljdwxsmncsbcno7xxia', u'genre': u'Pop', u'kind': u'sj#track', u'ar
tist': u'DJ MixMasters', u'durationMillis': u'28000'}, u'score': 2.762075662612915, u'type': u'1'}]} for field '<o
bj>' contains additional property 'clusterOrder' not defined by 'properties' or 'patternProperties' and additional
Properties  is False
```

**Comment by simon-weber** [comment]
Thanks!
