### ISSUE TITLE
example.py is not working

### ISSUE THREAD

**Issue by mrmaffen** [simon-weber/Unofficial-Google-Music-API#342]
Traceback (most recent call last):
  File "example.py", line 91, in <module>
    demonstrate()
  File "example.py", line 33, in demonstrate
    api = ask_for_credentials()
  File "example.py", line 24, in ask_for_credentials
    logged_in = api.login(email, password)
TypeError: login() takes exactly 4 arguments (3 given)

**Comment by austinberard** [comment]
Having the same problem, it seems the example needs the android_ID.

**Comment by simon-weber** [comment]
Thanks for pointing this out! It turns out that android_id is not actually needed =)
